- server:
    server_name: example.com
    listen: 127.0.0.6:2222
    root: ./
    max_body_size: 500M
    error: 404 ./CustomErrors/404.html
    # directory in post cgi

    - location:
        dir_listing: on
        allow_methods: POST GET
        root: ./myWebsite
        index: index.html
        cgi_path: py /usr/bin/python3
        cgi_path: php /usr/bin/php-cgi
        cgi_path: sh /usr/bin/sh
        auto_index: on
        upload: /upload

    - location /upload:
        dir_listing: on
        allow_methods: GET
        root: ./myWebsite/upload

- server:
    server_name: localhost
    listen: 127.0.0.1:2222
    root: ./
    error: 404 /path/to/404.html

    - location:
        dir_listing: off
        allow_methods: POST GET
        root: ./avito
        index: test.html items.html
        auto_index: on
        upload: /uploads

    - location /about:
        dir_listing: on
        allow_methods: POST  GET
        root: ./avito
        index: about.html flow.html
        auto_index: on
        upload: /uploads


    - location /contact:
        dir_listing: on
        allow_methods: GET POST
        root: ./avito
        index: contact.html flow.php test.html
        auto_index: on
        # upload: /upload
