- server:
    server_name: server1
    listen: 127.0.0.1:8081
    root: ./myWebsite
    max_body_size: 1G
    error: 404 ./location/404.html

    - location:
        dir_listing: on
        allow_methods: POST GET DELETE
        index: index.html
        auto_index: on
        # cgi_path: php /usr/bin/php-cgi
        upload: /upload

- server:
    server_name: server2
    listen: 127.0.0.1:8080
    root: ./avito

    - location /:
        dir_listing: on
        allow_methods: POST GET
        index: index.html
        auto_index: on
        upload: /upload


- server:
    server_name: dd
    listen: 127.0.0.1:1515
    root: ./toDelete

    - location /:
        dir_listing: on
        allow_methods: DELETE GET
        root: ./toDelete
        index: index.html
        auto_index: on
