- server:
    server_name: webser

    listen: 127.0.0.1:4444

    root: ./test
    index: index.html

    cgi_path: py /usr/bin/python3
    cgi_path: php /Users/maneddam/.local/bin/php-cgi
    cgi_path: purl /usr/bin/purl

    default_dir_file: error_pages/dir_ans_file.html

    allow_methods: GET POST DELETE

    Error: 404 ./error_pages/404.html

    upload: ./upload

    - location:

        dir_listing: location1
        allow_methods: GET POST location 1
        root: ./www location1


    - location /portfolio:
        dir_listing: off location2
        allow_methods: GET location2
        root: ./www/portfolio location2
        auto_index: on location2
        index: index.html location2

    - location /cgi:

        dir_listing: on location3
        allow_methods: GET POST location3
        root: ./www/cgi location3
        auto_index: off location3


    - location /gallery:
        allow_methods: GET location4
        root: ./www/gallery location4
        index: index.html location4
        auto_index: on location4

    - location /iphone:
        allow_methods: GET location5
        root: ./www/gallary location5
        auto_index: on location5
