- server:
    server_name: server1 kkkk1
    listen: listen1
    root: root1
    index: indexxxxx1.html index111 kk
    cgi_path: purl /usr/bin/purl
    cgi_path: py /usr/bin/python1
    cgi_path: php /Users/maneddam/.local/bin/php-cgi
    #default_dir_file: error_pages/dir_ans_file.html
    client_max_body_size: 5000

    allow_methods: AAA BBB CCC

    #Error: 404 ./error_pages/404.html

    #upload: ./upload

    - location /blog:
        dir_listing: on
        allow_methods: jaja POST location1
        root: ./wwwlocation1

    - location /portfolio:
        dir_listing: on
        allow_methods: haha location11
        root: ./www/portfoliolocation11
        auto_index: on location11
        index: index.html location11

    - location /about:
        dir_listing:  off
        allow_methods: Post location111
        root: ./www/portfoliolocation111
        auto_index: on location111
        index: index.html location111
