- server:
    server_name: server1 kkkk1
    listen: 127.0.0.1:9090
    root: /
    error: 404 /path/to/404.html


      - location /myWebsite:
          dir_listing: on
          allow_methods: GET
          root: ./myWebsite
          index: loc1.html flow.php
          cgi_path: py /usr/bin/python3
          cgi_path: php /Users/maneddam/.local/bin/php-cgi
          cgi_path: purl /usr/bin/purl
          auto_index: on
          upload: ./upload
          max_body_size: 4000M

      - location /myWebsite:
          dir_listing: on
          allow_methods: GET
          root: ./myWebsite
          index: loc1.html flow.php
          cgi_path: py /usr/bin/python3
          cgi_path: ff /Users/maneddam/.local/bin/php-cgi
          #        cgi_path: purl /usr/bin/purl
          #        cgi_path: sh /usr/bin/purl
          auto_index: on
          upload: ./upload
          max_body_size: 4000M