- server:
#    server_name: server1 kkkk1
    listen: listen1
    root: root1
    index: indexxxxx1.html index111 kk
    cgi_path: py /usr/bin/python1
    cgi_path: php /Users/maneddam/.local/bin/php-cgi
    cgi_path: purl /usr/bin/purl
    #default_dir_file: error_pages/dir_ans_file.html
#    client_max_body_size: 5000

    allow_methods: TEST POST DELETE

    #Error: 404 ./error_pages/404.html

    #upload: ./upload

    - location /blog:
        dir_listing: on
        allow_methods: GET POST location1
        root: ./wwwlocation1

    - location /portfolio:
        dir_listing: on
        allow_methods: GET location11
        root: ./www/portfoliolocation11
        auto_index: on location11
        index: index.html location11

    - location /about:
        dir_listing:  off
        allow_methods: Post location111
        root: ./www/portfoliolocation111
        auto_index: on location111
        index: index.html location111


- server:
    server_name: webserv
    listen: 127.0.0.1:4444
    root: ./test
    index: index.html
    cgi_path: py /usr/bin/python3
    cgi_path: php /Users/hlahrach/.local/bin/php-cgi
    cgi_path: purl /usr/bin/purl
    #      default_dir_file: error_pages/dir_ans_file.html
    allow_methods: GET POST DELETE
#    client_max_body_size: 999
    #      error_pages: 404 ./error_pages/404.html
    upload: ./upload
    - location /:

        dir_listing: on
        allow_methods: GET POST
        root: ./www


    - location /portfolio:

        dir_listing: off
        allow_methods: GET
        root: ./www/portfolio
        index: index.html
        auto_index: on


    - location /cgi:

        dir_listing: on
        allow_methods: GET POST
        root: ./www/cgi
        auto_index: off


    - location /gallary:
        allow_methods: GET
        root: ./www/gallary
        index: index.html
        auto_index: on


    - location /finexo:
        allow_methods: GET
        root: ./www/finexo
        index: index.html
        auto_index: on