- server:
    server_name: localhost
    listen: 127.0.0.1:9090
    root: ./myWebsite
    max_body_size: 1G
    error: 404 ./CustomErrors/404.html

    - location:
        dir_listing: on
        allow_methods: POST GET
        root: ./myWebsite
        index: index.html
        cgi_path: py /usr/bin/python3
        cgi_path: php /usr/bin/php-cgi
        auto_index: on
        upload: /upload


- server:
    server_name: serv1
    listen: 127.0.0.1:2222
    root: ./avito

    - location /:
        dir_listing: on
        allow_methods: POST GET
        root: ./avito
        index: index.html
        auto_index: on
        upload: /upload


- server:
    server_name: serv2
    listen: 127.0.0.1:1515
    root: ./toDelete

    - location /:
        dir_listing: on
        allow_methods: DELETE GET
        root: ./toDelete
        index: index.html
        auto_index: on
