- server:
    server_name: servername1 kkkk1
    listen: 127.0.0.1:9090
    root: ./
    error: 404 /path/to/404.html

    - location:
        dir_listing: on
        allow_methods: POST GET
        root: ./myWebsite
        index: loc1.htm127.0.0.1:9090/home/testl flow.php
        cgi_path: py /usr/bin/python3
        cgi_path: php /Users/maneddam/.local/bin/php-cgi
        cgi_path: purl /usr/bin/purl
        auto_index: off
        upload: /uploads
        


    - location /about:
        dir_listing: off
        allow_methods: GET POST
        root: ./myWebsite
        index: loc1.html flow.php  gg ds
        cgi_path: py /usr/bin/python3
        cgi_path: php /Users/maneddam/.local/bin/php-cgi
        cgi_path: purl /usr/bin/purl
        auto_index: off
        upload: /upload
        

    - location /home/test:
        dir_listing: off
        allow_methods: GET POST
        root: ./myWebsite
        index: loc1.html flow.php  gg ds
        cgi_path: py /usr/bin/python3
        cgi_path: php /Users/maneddam/.local/bin/php-cgi
        cgi_path: purl /usr/bin/purl
        auto_index: on
        upload: /upload

    - location /upload:
        dir_listing: on
        allow_methods: GET
        root: ./myWebsite
