- server:
#    server_name: server1 kkkk1
    listen: listen1
    root: root1
    index: indexxxxx1.html index111 kk
    #cgi_path: py /usr/bin/python3
    #cgi_path: php /Users/maneddam/.local/bin/php-cgi
    #cgi_path: purl /usr/bin/purl
    #default_dir_file: error_pages/dir_ans_file.html

    allow_methods: TEST POST DELETE

    #Error: 404 ./error_pages/404.html

    #upload: ./upload

    - location /blog:
        dir_listing: on
        allow_methods: GET POST location1
        root: ./wwwlocation1

    - location /portfolio:
        dir_listing: on
        allow_methods: GET location11
        root: ./www/portfoliolocation11
        auto_index: on location11
        index: index.html location11

    - location /about:
        dir_listing:  on
        allow_methods: Post location111
        root: ./www/portfoliolocation111
        auto_index: on location111
        index: index.html location111

- server:
    server_name: server2 kkkk2
    listen: listen2
    root: root2
    allow_methods: Post POST DELETE
    index: index2.html index222

    - location /dd:
        dir_listing: off
        allow_methods: GET location2
        root: ./www/portfoliolocation2
    - location /lherba:
        dir_listing: off
        allow_methods: GET location2
        root: ./www/portfoliolocation2


- server:
    index: index3.html index333
    root: root3
    server_name: server3 kkkk3

    listen: listen3
    allow_methods: DELETE POST DELETE
    - location /akheruahd1:
        dir_listing: on
        allow_methods: GET location2
        root: ./www/portfoliolocation2
    - location /akheruahd2:
        dir_listing: on
        allow_methods: GET location2
        root: ./www/portfoliolocation2

