- server:
    server_name: server1 kkkk1
    listen: 127.0.0.1:9090
    index: indexxxxx1.html index111
    cgi_path: py /usr/bin/python3
    cgi_path: php /Users/maneddam/.local/bin/php-cgi
    cgi_path: purl /usr/bin/purl
    default_dir_file: error_pages/dir_ans_file.html
    root: /
    allow_methods: GET POST DELETE

    upload: ./upload

    - location /blog:
        dir_listing: on
        allow_methods: GET POST
        root: ./wwwlocation1

    - location /portfolio:
        dir_listing: on
        allow_methods: GET
        root: ./www/portfoliolocation11
        auto_index: on location11
        index: index.html location11

    - location /about:
        dir_listing:  on
        allow_methods: GET DELETE
        root: ./www/portfoliolocation111
        auto_index: on location111
        index: index.html location111

- server:
    server_name: server2 kkkk2
    listen: 5555
    root: root2
    allow_methods: GET POST DELETE
    index: index2.html index222


    - location /dd:
        dir_listing: off
        allow_methods: GET
        root: ./www/portfoliolocation2
    - location /lherba:
        dir_listing: off
        allow_methods: GET
        root: ./www/portfoliolocation2



- server:
    index: index3.html index333
    listen: 2222
    root: root3
    server_name: server3 kkkk3

    error: 404 ./error_pages/404.html
    error: 302 ./error_pages/404.html

    allow_methods: DELETE POST GET
    - location /akheruahd1:
        dir_listing: on
        allow_methods: GET POST
        root: ./www/portfoliolocation2
    - location /akheruahd2:
        dir_listing: on
        allow_methods: GET
        root: ./www/portfoliolocation2