- server:
    server_name: server1
    listen: listen1
    root: root1


    - location /blog:
        dir_listing: on
        allow_methods: GET POST location1
        root: ./wwwlocation1

    - location /portfolio:
        dir_listing: on
        allow_methods: GET location11
        root: ./www/portfoliolocation11
        auto_index: on location11
        index: index.html location11

    - location /about:
        dir_listing:  on
        allow_methods: GET location111
        root: ./www/portfoliolocation111
        auto_index: on location111
        index: index.html location111

- server:
    root: root2
    - location /dd:
        dir_listing: off
        allow_methods: GET location2
        root: ./www/portfoliolocation2
    - location /lherba:
        dir_listing: off
        allow_methods: GET location2
        root: ./www/portfoliolocation2

- server:
    root: root2
    - location /akheruahd1:
        dir_listing: on
        allow_methods: GET location2
        root: ./www/portfoliolocation2
    - location /akheruahd2:
        dir_listing: off
        allow_methods: GET location2
        root: ./www/portfoliolocation2
    - location /hahahahhahah:

