- server:
    server_name: server1
    listen: listen1
    root: root1
    index: index.html
    cgi_path: py /usr/bin/python3
    cgi_path: php /Users/maneddam/.local/bin/php-cgi
    cgi_path: purl /usr/bin/purl
    default_dir_file: error_pages/dir_ans_file.html

    allow_methods: GET POST DELETE

    Error: 404 ./error_pages/404.html

    upload: ./upload

    - location /blog:
        dir_listing: location1
        allow_methods: GET POST location1
        root: ./wwwlocation1

    - location /portfolio:
        dir_listing: off location11
        allow_methods: GET location11
        root: ./www/portfoliolocation11
        auto_index: on location11
        index: index.html location11

    - location /about:
        dir_listing: off location111
        allow_methods: GET location111
        root: ./www/portfoliolocation111
        auto_index: on location111
        index: index.html location111

- server:
    root: root2
    allow_methods: GET POST DELETE
    - location /dd:
        dir_listing: off location2
        allow_methods: GET location2
        root: ./www/portfoliolocation2
    - location /lherba:
        dir_listing: off location2
        allow_methods: GET location2
        root: ./www/portfoliolocation2

