- server:
    server_name: localhost
    listen: 127.0.0.1:9090
    root: ./avito
    max_body_size: 2G
    error: 404 ./CustomErrors/404.html

    - location:
        dir_listing: on
        allow_methods: GET POST
        index: index.html
        cgi_path: py /usr/bin/python3
        cgi_path: php /usr/bin/php-cgi
        auto_index: on
        upload: /upload
        
    - location /upload/:
        dir_listing: on
        allow_methods: GET 
        root: ./avito/upload
        auto_index: off
    


- server:
    server_name: serv1
    listen: 127.0.0.1:2222
    root: ./myWebsite

    - location /:
        dir_listing: on
        allow_methods: POST GET
        root: ./myWebsite
        cgi_path: php /usr/bin/php-cgi
        cgi_path: py /usr/bin/python3
        index: index.html
        auto_index: on
        upload: /upload


- server:
    server_name: serv2
    listen: 127.0.0.1:1515
    root: ./toDelete

    - location /:
        dir_listing: on
        allow_methods: DELETE GET
        root: ./toDelete
        auto_index: off