- server:
    server_name: server1 kkkk1
    listen: 127.0.0.1:9090
    #index: indexxxxx1.html index111
    default_dir_file: error_pages/dir_ans_file.html
    root: /
    allow_methods: GET POST DELETE

    - location /path:
        dir_listing: off
        allow_methods: GET POST
        root: ./wwwlocation1
        index: loc1.html flow.php  gg ds
        cgi_path: py /usr/bin/python3
        cgi_path: php /Users/maneddam/.local/bin/php-cgi
        cgi_path: purl /usr/bin/purl
        auto_index: off
        upload: ./upload

