- server:
    server_name: serv2
    listen: 127.0.0.1:2223
    root: ./myWebsite
    max_body_size: 1G
    error: 404 ./CustomErrors/404.html

    - location:
        dir_listing: on
        allow_methods: POST GET DELETE
        root: ./myWebsite
        index: index.html
        cgi_path: py /usr/bin/python3
        cgi_path: php /usr/bin/php-cgi
        auto_index: on
        upload: /upload


- server:
    server_name: serv1
    listen: 127.0.0.1:2222
    root: ./avito
    error: 404 /path/to/404.html

    - location /contact/:
        dir_listing: on
        allow_methods: POST GET
        root: ./avito
        index: index.html
        cgi_path: py /usr/bin/python3
        cgi_path: php /usr/bin/php-cgi
        auto_index: on
        upload: /upload



- server:
    server_name: serv1
    listen: 127.0.0.1:2222
    root: ./avito/serv1
    max_body_size: 1M
    error: 404 ./CustomErrors/404.html

    - location:
        dir_listing: on
        allow_methods: POST GET
        root: ./myWebsite
        index: index.html
        cgi_path: py /usr/bin/python3
        cgi_path: php /usr/bin/php-cgi
        auto_index: on
        upload: /upload
