#!/bin/bash

echo "Content-type: text/html"
echo ""
echo "<html>"
echo "<head>"
echo "<title>CGI Script Example</title>"
echo "</head>"
echo "<body>"
echo "<h1>Hello from CGI Script!</h1>"
echo "<h1>Hello from CGI Script!</h1>"
echo "<h1>Hello from CGI Script!</h1>"
echo "<h1>Hello from CGI Script!</h1>"
echo "<h1>Hello from CGI Script!</h1>"
echo "<p>This is a simple CGI script executed by the C++ server.</p>"
echo "</body>"
echo "</html>"
